//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18046
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class evec_api {
    
    private evec_apiType[] marketstatField;
    
    private decimal versionField;
    
    private string methodField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("type", IsNullable=false)]
    public evec_apiType[] marketstat {
        get {
            return this.marketstatField;
        }
        set {
            this.marketstatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class evec_apiType {
    
    private evec_apiTypeBuy buyField;
    
    private evec_apiTypeSell sellField;
    
    private evec_apiTypeAll allField;
    
    private int idField;
    
    /// <remarks/>
    public evec_apiTypeBuy buy {
        get {
            return this.buyField;
        }
        set {
            this.buyField = value;
        }
    }
    
    /// <remarks/>
    public evec_apiTypeSell sell {
        get {
            return this.sellField;
        }
        set {
            this.sellField = value;
        }
    }
    
    /// <remarks/>
    public evec_apiTypeAll all {
        get {
            return this.allField;
        }
        set {
            this.allField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class evec_apiTypeBuy {
    
    private float volumeField;
    
    private float avgField;
    
    private float maxField;
    
    private float minField;
    
    private float stddevField;
    
    private float medianField;
    
    private float percentileField;
    
    /// <remarks/>
    public float volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    public float avg {
        get {
            return this.avgField;
        }
        set {
            this.avgField = value;
        }
    }
    
    /// <remarks/>
    public float max {
        get {
            return this.maxField;
        }
        set {
            this.maxField = value;
        }
    }
    
    /// <remarks/>
    public float min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    public float stddev {
        get {
            return this.stddevField;
        }
        set {
            this.stddevField = value;
        }
    }
    
    /// <remarks/>
    public float median {
        get {
            return this.medianField;
        }
        set {
            this.medianField = value;
        }
    }
    
    /// <remarks/>
    public float percentile {
        get {
            return this.percentileField;
        }
        set {
            this.percentileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class evec_apiTypeSell {
    
    private float volumeField;
    
    private float avgField;
    
    private float maxField;
    
    private float minField;
    
    private float stddevField;
    
    private float medianField;
    
    private float percentileField;
    
    /// <remarks/>
    public float volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    public float avg {
        get {
            return this.avgField;
        }
        set {
            this.avgField = value;
        }
    }
    
    /// <remarks/>
    public float max {
        get {
            return this.maxField;
        }
        set {
            this.maxField = value;
        }
    }
    
    /// <remarks/>
    public float min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    public float stddev {
        get {
            return this.stddevField;
        }
        set {
            this.stddevField = value;
        }
    }
    
    /// <remarks/>
    public float median {
        get {
            return this.medianField;
        }
        set {
            this.medianField = value;
        }
    }
    
    /// <remarks/>
    public float percentile {
        get {
            return this.percentileField;
        }
        set {
            this.percentileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class evec_apiTypeAll {
    
    private float volumeField;
    
    private float avgField;
    
    private float maxField;
    
    private float minField;
    
    private float stddevField;
    
    private float medianField;
    
    private float percentileField;
    
    /// <remarks/>
    public float volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    public float avg {
        get {
            return this.avgField;
        }
        set {
            this.avgField = value;
        }
    }
    
    /// <remarks/>
    public float max {
        get {
            return this.maxField;
        }
        set {
            this.maxField = value;
        }
    }
    
    /// <remarks/>
    public float min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    public float stddev {
        get {
            return this.stddevField;
        }
        set {
            this.stddevField = value;
        }
    }
    
    /// <remarks/>
    public float median {
        get {
            return this.medianField;
        }
        set {
            this.medianField = value;
        }
    }
    
    /// <remarks/>
    public float percentile {
        get {
            return this.percentileField;
        }
        set {
            this.percentileField = value;
        }
    }
}
